### ISSUE TITLE
adding HmIP-WTH-B-2 devicedump

### ISSUE THREAD

**Issue by mamugit** [hahn-th/homematicip-rest-api#529]
Hi,

it would be great if HmIP-WTH-B-2 Display/Wall-Thermostate could be added to the Rest-API; device-dump is here:
https://gist.github.com/mamugit/c1660662d84378b045b32831f1014171

**Comment by hahn-th** [comment]
I guess youre talking about the Integration in HomeAssistant?
I currently working on make the HomeAssistant work with a new release of this library. Takes a while cause i have to rewrite lots of code.
After that, all the devices will work.

If you wanna help testing: homematicip-rest-api@outlook.com or discord!

**Comment by mamugit** [comment]
no, this was due to the fact that HmIP-WTH-B-2 is marked not supported on your entry page for the restAPI on github.
no tickbox marked
meanwhile I had more time to test and the cli is working properly with HmIP-WTH-B-2.
So due to my understanding it should be supported by your API and CLI
maybe the dump is useful for you anyways.

**Comment by hahn-th** [comment]
Okay nice!

If you like you could try out the new cli.
Would help me a lot!
pip install homematicip==1.1.0.post1.dev53

**Comment by mamugit** [comment]
did a quick test with 1.1.0.post1.dev53:

generating auth token -> working
hmip list rssi -> working
hmip list last-status-update -> working
hmip list firmware -> working
hmip run dump filename.txt -> working




hmip list devices -> failure

Devices:
Traceback (most recent call last):
  File "/home/user/.local/bin/./hmip", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/homematicip/cli/hmip.py", line 151, in devices
    output = generate_output_device(device, format_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/homematicip/cli/output_formatter/formatter.py", line 17, in generate_output_device
    return _generate_output(device, output_format_config.device_attributes)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_attributes'




... maybe Data-Output of prssi is causing this; since a while I get prssi value= None; rssiPeerValue(None)





hmip list groups -> failure

Groups:
Traceback (most recent call last):
  File "/home/user/.local/bin/./hmip", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/homematicip/cli/hmip.py", line 169, in groups
    output = generate_output_group(group, format_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/homematicip/cli/output_formatter/formatter.py", line 12, in generate_output_group
    return _generate_output(group, output_format_config.group_attributes)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group_attributes'

**Comment by hahn-th** [comment]
This is fixed: https://pypi.org/project/homematicip/1.1.0.post1.dev54/

**Comment by mamugit** [comment]
great! hmip list devices and hmip list groups is working with  1.1.0.post1.dev54 !!

**Comment by lackas** [comment]
Device is supported in the library (maps to `WallMountedThermostatBasicHumidity`) and works in Home Assistant via heating groups and sensors. CLI issues were fixed in 2024. Closing.
