### ISSUE TITLE
Error "unexpected keyword argument 'extra_headers'" causing temporary bans - Retrying in 1 seconds

### ISSUE THREAD

**Issue by Robin19777** [hahn-th/homematicip-rest-api#546]
Since I have updated to the latest version of Home Assistant the Integration causes temporary bans. Support of EQ3 said, that it is the Home Assistant Integration. I activated the debug log and got the following lines, which repeats all the time:

```
2024-11-10 12:44:07.011 ERROR (MainThread) [homematicip.aio.connection] BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homematicip/aio/connection.py", line 114, in _connect_to_websocket
    self.socket_connection = await asyncio.wait_for(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
2024-11-10 12:44:07.048 ERROR (MainThread) [homeassistant.components.homematicip_cloud.hap] Error connecting to HomematicIP with HAP  XXX   . Retrying in 1 seconds
```

Do you have a solution?

**Comment by hahn-th** [comment]
Could you please try get a connection via the cli?
https://hahn-th.github.io/homematicip-rest-api/gettingstarted.html

**Comment by hahn-th** [comment]
Looks like eq-3 has changed there handshake procedure.... 

What's the Version of your HAP?

**Comment by Robin19777** [comment]
> Looks like eq-3 has changed there handshake procedure....
> 
> What's the Version of your HAP?

Core
2024.11.1
Supervisor
2024.11.3
Operating System Frontend
20241106.2

HmIP Integration is latest version

**Comment by hahn-th** [comment]
And the version of your Homematic IP Access Point? You could see it in the homematic app.
Have you tried connecting via the CLI?

**Comment by Robin19777** [comment]
App Version 3.2.6 hap 2.0.32
Where can I run this cli script? Do i have to use it in Docker container of home assistant? 
Edit: The actors are working in home assistant, unless the connection is not temporary refused.

**Comment by hahn-th** [comment]
Is it working for you again?

**Comment by juratau** [comment]
Hello, this my first entry, so, sorry if I am doing something wrong ....

I have the identical "Error connecting to HomematicIP with HAP xxx ...." issue since 12-Nov and I have tried dozens of actions since then to solve this problem, without any success so far.

The Homematic IP integration is running since approx. 1 year without any problems.
The issue occured first on 12-Nov directly after updating HomeAssistant from 2024.11.0 to 2024.11.1. The dashboard was not anymore updated with current HmIP sensor status.
On 13-Nov I recognized also the "Drosselung Rest aktiv" messages through the HmIP App, which came up dozens of times since then (but were healed again after more that 15 min. inactivity).

In the meantime I have tried for example:
- restore HA to previous 2024.11.0 backup versions
- dozens of HA reboots
- switched off & on HmIP Access Point several times
- deactivated automations in order to reduce traffic
- deleted and reinstalled the "HomematicIP Cloud" integration via the HA Integrations UI.
- updated to HA 2024.11.2
- etc.

Result is ALWAYS the same:
As soon as the HmIP integration starts to work, I see the following errors bumping up in the HA protocol:
###########################################
.....
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
2024-11-16 16:38:37.370 ERROR (MainThread) [homeassistant.components.homematicip_cloud.hap] Error connecting to HomematicIP with HAP xxxxxxxx. Retrying in 32 seconds
2024-11-16 16:39:09.476 WARNING (MainThread) [homematicip.device] Optional Device Feature 'IOptionalFeatureOperationDays' is not yet supported
2024-11-16 16:39:09.477 WARNING (MainThread) [homematicip.device] Optional Device Feature 'IOptionalFeatureOperationDays' is not yet supported
2024-11-16 16:39:09.478 WARNING (MainThread) [homematicip.device] Optional Device Feature 'IOptionalFeatureOperationDays' is not yet supported
2024-11-16 16:39:09.479 WARNING (MainThread) [homematicip.device] Optional Device Feature 'IOptionalFeatureOperationDays' is not yet supported
2024-11-16 16:39:09.487 ERROR (MainThread) [homematicip.aio.connection] BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homematicip/aio/connection.py", line 114, in _connect_to_websocket
    self.socket_connection = await asyncio.wait_for(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 442, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 368, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
2024-11-16 16:39:09.489 ERROR (MainThread) [homeassistant.components.homematicip_cloud.hap] Error connecting to HomematicIP with HAP xxxxxxxx. Retrying in 64 seconds
.....
###########################################

I can toggle HmIP switches in HomeAssistant (often with major delays ...) and I can see the switch status update in the HmIP App.
However, if I toggle switches in the HmIP App, HomeAssistant will not update the status.
So it is some kind of one-way communication ...

Looks like something has broken during the update to HA 2024.11.1, either on HA/HmIP or on EQ-3 side.

My system:
- HmIP Access Point:  Firmware 3.0.18
- HmIP App version 3.2.6
- 21 different physical HmIP devices
- HomeAssistant installed on RaspberryPi4
- Core 2024.11.2
- Supervisor 2024.11.2
- Operating System 13.2
- Frontend 20241106.2

Please help!

Thank you

**Comment by Robin19777** [comment]
> Is it working for you again?

I have activated the Integration again. IT works now, since 3 hours without temporary ban. I will have a Look at it and report.

**Comment by Robin19777** [comment]
Hello, quick update: the problem still exists.

**Comment by LucTs** [comment]
@hahn-th 
I lost connection to HMIP since yesterday eveing. Seems to be connected to the latest version/release.
Just restarted HMIP but same issue. See below logs

`_Logger: homeassistant.components.homematicip_cloud.hap
Quelle: components/homematicip_cloud/hap.py:195
Integration: HomematicIP Cloud ([Dokumentation](https://www.home-assistant.io/integrations/homematicip_cloud), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+homematicip_cloud%22))
Erstmals aufgetreten: 08:15:06 (7 Vorkommnisse)
Zuletzt protokolliert: 08:16:10

    Error connecting to HomematicIP with HAP 30xxx. Retrying in 4 seconds
    Error connecting to HomematicIP with HAP 30xxx. Retrying in 8 seconds
    Error connecting to HomematicIP with HAP 30xxx. Retrying in 16 seconds
    Error connecting to HomematicIP with HAP 30xxx. Retrying in 32 seconds
    Error connecting to HomematicIP with HAP 30xxx. Retrying in 64 seconds_`


**Home Assistant Versions:**
Core 2024.11.2
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

**HMIP AP Version:**
3.0.18

**Comment by LucTs** [comment]
Additional error message:

`Logger: homematicip.aio.connection
Quelle: /usr/local/lib/python3.12/site-packages/homematicip/aio/connection.py:127
Erstmals aufgetreten: 08:20:49 (3 Vorkommnisse)
Zuletzt protokolliert: 08:22:26
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homematicip/aio/connection.py", line 114, in _connect_to_websocket
    self.socket_connection = await asyncio.wait_for(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 442, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 368, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'`

**Comment by hahn-th** [comment]
Hi. There is already an open PR in HomeAssistant: https://github.com/home-assistant/core/pull/130824

The way the websockets lib was used is deprecated. And they switched with release of websockets 14.0 to use the new way as the default way. So the old one doesn't work anymore. 

I think i can close this issue. There is already a homematicip release 1.1.3, which fixes the problem.
